### ISSUE TITLE
Integers without formats don't generate default values in code

### ISSUE THREAD

**Issue by plk** [RSuter/NJsonSchema#869]
Take the following YAML spec:

```
someparam:
  type: integer
  default: 4
```

the default value is missing in code/controller generation unless an explicit format is given:

```
someparam:
  type: integer
  format: int32
  default: 4
```

The openapi spec says that format is optional ...

See also RSuter/NSwag#1879

**Comment by RSuter** [comment]
Can you provide a more complete sample? 

According to this test, it should work: https://github.com/RSuter/NJsonSchema/blob/7c55e6c1453b371d4a7ca117b61f2c7cff156a63/src/NJsonSchema.CodeGeneration.Tests/DefaultValueGeneratorTests.cs#L26

Is this only a problem with Swagger/OpenAPI parameters? In this case it never generates a default value for me, even if I set the "format" to "int32"

**Comment by plk** [comment]
This is code generation from an openapi spec. In fact these parameters are parameters inside an object:

```
  ComplexType:
    type: object
    parameters:
      someint:
        type: int
        default: 4
```

For me, without the `format: int32`, no default value is generated in C# controller output, with it, it's fine. I can check again later and look at that test.
